
INCLUDEDIR = ../../include

CC = gcc
CFLAGS = -c -O2 -Wall -I$(INCLUDEDIR)


OBJFILES = driver.o
INCLUDEFILES = $(INCLUDEDIR)*.h


#all: $(OBJFILES)
all:


#drivers.o: drivers.asm $(INCLUDEFILES)
#	$(ASM) $(ASMFLAGS) -o $@ $<


clean:
	rm -f *.o
